import { getFooter } from "@lib/contentful/getFooter";
import { getNavigationMenu } from "@lib/contentful/getNavigationMenu";
import { getSingleEmailForm } from "@lib/contentful/getSingleEmailForm";
import { Footer } from "@src/components/shared/footer";
import { Navbar } from "@src/components/shared/navbar";
import { routing } from "@src/i18n/routing";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Nunito_Sans } from "next/font/google";
import { draftMode } from "next/headers";
import { notFound } from "next/navigation";
import "../globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
});

export const metadata: Metadata = {
  title: "Iglesia de Cristo Redentor",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  readonly children: React.ReactNode;
  readonly params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const { isEnabled } = await draftMode();
  const navMenu = await getNavigationMenu("Main menu", locale);
  const footerContent = await getFooter(locale, isEnabled);
  const subscribeContent = await getSingleEmailForm(
    "single-email-subscribe",
    locale,
    isEnabled,
  );

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${nunitoSans.variable} font-sans antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <Navbar menuItems={navMenu} />
          {children}
          <Footer content={footerContent} subscribeContent={subscribeContent} />
        </NextIntlClientProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
